// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTfullDemo.Data;

namespace RESTfullDemo.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20200329065305_init_20200329")]
    partial class init_20200329
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("RESTfullDemo.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3aceb6c1-edec-4a0a-ab4e-2b23a19b3da3"),
                            Introduction = "阿里巴巴(中国)有限公司成立于2007年03月26日，注册地位于杭州市西湖区西斗门路3号天堂软件园A幢10楼G座，法人代表为张勇。",
                            Name = "阿里巴巴"
                        },
                        new
                        {
                            Id = new Guid("1721aa41-aad6-4e6b-be2e-fd3e7d0f7129"),
                            Introduction = "深圳市腾讯计算机系统有限公司成立于1998年11月11日，注册地位于深圳市南山区粤海街道麻岭社区科技中一路腾讯大厦35层，法人代表为马化腾。",
                            Name = "腾讯"
                        },
                        new
                        {
                            Id = new Guid("1bccb001-9b51-45eb-8e3f-7b9ea54a3d35"),
                            Introduction = "北京字节跳动科技有限公司成立于2012年，是最早将人工智能应用于移动互联网场景的科技企业之一，是中国北京的一家信息科技公司，地址位于北京市海淀区知春路甲48号。",
                            Name = "字节跳动"
                        },
                        new
                        {
                            Id = new Guid("c04a8a8a-bab3-48d6-b6c9-24dddc9210e5"),
                            Introduction = "北京百度网讯科技有限公司成立于2001年06月05日，注册地位于北京市海淀区上地十街10号百度大厦2层，法人代表为梁志祥。",
                            Name = "百度"
                        },
                        new
                        {
                            Id = new Guid("1328bf95-f6d3-4b1d-ad67-ca3c7b8203d6"),
                            Introduction = "京东（股票代码：JD），中国自营式电商企业，创始人刘强东担任京东集团董事局主席兼首席执行官。",
                            Name = "京东"
                        });
                });

            modelBuilder.Entity("RESTfullDemo.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03ecefd0-2892-468d-b94f-41e2b61b1d56"),
                            CompanyId = new Guid("3aceb6c1-edec-4a0a-ab4e-2b23a19b3da3"),
                            DateOfBirth = new DateTime(1983, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "001",
                            FirstName = "张",
                            Gender = 1,
                            LastName = "勇"
                        },
                        new
                        {
                            Id = new Guid("14a3592a-96eb-401c-a3f1-f9d257704e68"),
                            CompanyId = new Guid("3aceb6c1-edec-4a0a-ab4e-2b23a19b3da3"),
                            DateOfBirth = new DateTime(1989, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "002",
                            FirstName = "蒋",
                            Gender = 2,
                            LastName = "芳"
                        },
                        new
                        {
                            Id = new Guid("2e31d15d-0503-463c-b97a-429953872df9"),
                            CompanyId = new Guid("3aceb6c1-edec-4a0a-ab4e-2b23a19b3da3"),
                            DateOfBirth = new DateTime(1983, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "003",
                            FirstName = "郑",
                            Gender = 2,
                            LastName = "俊芳"
                        });
                });

            modelBuilder.Entity("RESTfullDemo.Entities.Employee", b =>
                {
                    b.HasOne("RESTfullDemo.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
